CREATE TABLE USER (
USER_ID	int	NOT NULL primary KEY AUTO_INCREMENT,
USER_NAME	varchar(50)	NOT NULL,		
LOGIN	INT UNIQUE	NOT NULL,	
PASSWORD int NOT NULL,
REG_DATE DATE NOT NULL,
COMPANY varchar(50),		
E_MAIL varchar(50));
CREATE TABLE substance(
SUBST_ENUM varchar(10)	NOT NULL primary KEY,
SUBST_NAME varchar(50)	NOT NULL,
COLOR int,
TYPE ENUM ('PRIMARY NUTRIENT', 'SECONDARY NUTRIENT', 'MICRONUTRIENT'));
CREATE TABLE FERTILIZER(
FERT_ID	int	NOT NULL primary KEY AUTO_INCREMENT,
FERT_NAME varchar(50)	NOT NULL,
TYPE varchar(50)	,
USER_ID	INT,
FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID));
CREATE TABLE FERT_COMPOS(	
FERT_ID	int	NOT NULL,
SUBST_ENUM varchar(10)	NOT NULL,
CONTENT	DECIMAL(5,4) NOT NULL,
PRIMARY KEY (FERT_ID, SUBST_ENUM),
FOREIGN KEY (FERT_ID) REFERENCES FERTILIZER (FERT_ID),
FOREIGN KEY (SUBST_ENUM) REFERENCES SUBSTANCE (SUBST_ENUM));
INSERT INTO SUBSTANCE (SUBST_NAME, SUBST_ENUM, COLOR, TYPE) 
VALUES ('Potassium oxide', 'K2O',8731495 , 'PRIMARY NUTRIENT');
INSERT INTO SUBSTANCE (SUBST_NAME, SUBST_ENUM, COLOR, TYPE) 
VALUES ('Nitrogen', 'N', 16772864, 'PRIMARY NUTRIENT');
INSERT INTO SUBSTANCE (SUBST_NAME, SUBST_ENUM, COLOR, TYPE) 
VALUES ('Phosphorus oxide', 'P2O5', 8945787, 'PRIMARY NUTRIENT');
INSERT INTO SUBSTANCE (SUBST_NAME, SUBST_ENUM, COLOR, TYPE) 
VALUES ('Sulphur oxide', 'SO3', 9313821, 'SECONDARY NUTRIENT');
INSERT INTO fertilizer (FERT_NAME, TYPE ,USER_ID)
VALUES('Monoammonium Phosphate', 'MAP 12-52', NULL);
INSERT INTO fertilizer (FERT_NAME, TYPE ,USER_ID)
VALUES('Diammonium Phosphate', 'DAP 18-47', NULL);